version: '3.8'
services:
  frontend:
    build: ./client/frontend
    ports:
      - "3001:3000"
  backend:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jmzpzvdu
      POSTGRES_PASSWORD: 8Lj-szyz9bkr20fUVpQ8QjxD7ttr1-hh
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: